# Generated by Django 3.1.5 on 2021-02-28 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0002_auto_20210228_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='timing',
            field=models.TimeField(default=datetime.time(7, 26, 5, 983851)),
        ),
    ]
