# Generated by Django 3.1.5 on 2021-02-28 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0005_auto_20210228_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='timing',
            field=models.TimeField(default=datetime.time(10, 33, 55, 111139)),
        ),
    ]
