# Generated by Django 3.1.5 on 2021-02-28 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0007_auto_20210228_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='timing',
            field=models.TimeField(default=datetime.time(10, 37, 18, 986765)),
        ),
    ]
