# Generated by Django 3.1.5 on 2021-02-28 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0008_auto_20210228_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='milkapp.customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='timing',
            field=models.TimeField(default=datetime.time(12, 7, 34, 725395)),
        ),
    ]
