# Generated by Django 3.1.5 on 2021-03-01 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0011_auto_20210228_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='timing',
            field=models.TimeField(default=datetime.time(6, 25, 38, 872288)),
        ),
    ]
