# Generated by Django 3.1.5 on 2021-03-01 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0012_auto_20210301_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='timing',
            field=models.TimeField(default=datetime.time(6, 28, 14, 748343)),
        ),
    ]
