# Generated by Django 3.1.5 on 2021-03-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0018_auto_20210304_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoyNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkapp.deliveryboy')),
            ],
        ),
    ]
