# Generated by Django 3.1.5 on 2021-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0020_deliveryboynotifications_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
    ]
