# Generated by Django 3.1.5 on 2021-03-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0021_auto_20210305_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
